/*
 * HEATING_ELEMENT_INTERFACE.h
 *
 * Created: 10/25/2022 12:34:13 AM
 *  Author: AHMED ELDEEB
 */ 


#ifndef HEATING_ELEMENT_INTERFACE_H_
#define HEATING_ELEMENT_INTERFACE_H_

void HEATING_ELEMENT_INIT(void);
void HEATING_ELEMENT_START(void);
void HEATING_ELEMENT_STOP(void);
void HEATING_ELEMENT_TOGGLE(void);

#endif /* HEATING_ELEMENT_INTERFACE_H_ */